title: Bryon's Blog
description: A blog by Bryon Miller
url: "https://bryonmiller.github.io"

# Official default Jekyll theme built into GitHub Pages
theme: hacker

# Plugins supported natively by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
